#!/bin/bash
#
# Copyright 2020 Red Hat, Inc.
#
# NAME
#     lab-test-mock - lab script for GE 7.4 on testing using mocks
#
# SYNOPSIS
#     lab-test-mock {start|finish}
#
#        start - verify prerequisites lab
#        finish - removes the resources and files created for lab
#
# DESCRIPTION
#     This script is used to start or conclude the chapter 7 section 4 guided exercise.
#
# CHANGELOG
#   * Thursday Nov 5th 2020 Manuel Aude Morales <maudemor@redhat.com>
#   - Start and Finish functions working.


PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

# Initialize and set some variables
run_as_root='true'

# Required by the do283 shlib
this='test-mock'
title='GE: Testing Microservices with Mock Frameworks'

declare -a valid_commands=(start finish)

function lab_start {
  ocp4_print_setup_header

  ocp4_grab_lab_files

  podman run -d --name "${this}-postgresql-expense" -p 5432:5432 -e \
    POSTGRESQL_PASSWORD=expenses_pwd -e POSTGRESQL_USER=expenses_user -e \
    POSTGRESQL_ADMIN_PASSWORD=admin_password -e POSTGRESQL_DATABASE=expenses \
    registry.access.redhat.com/rhscl/postgresql-10-rhel7:1
  ocp4_print_setup_footer

}

function lab_finish {

  ocp4_print_cleanup_header

  ocp4_cleanup_lab_files
  podman rm -f "${this}-postgresql-expense"

  ocp4_print_cleanup_footer

}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
