#!/bin/bash
#
# Copyright 2020 Red Hat, Inc.
#
# NAME
#     lab-secure-jwt - lab script for GE 8.4
#
# SYNOPSIS
#     lab-secure-jwt {start|finish}
#
#        start - verify prerequisites lab
#        finish - removes the resources and files created for lab
#
# DESCRIPTION
#     This script is used to start or conclude the chapter 8 section 4 guided exercise.
#
# CHANGELOG
#   * Mon Nov 16 2020 Marek Czernek <mczernek@redhat.com>
#   - Initial commit


PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

# Initialize and set some variables
run_as_root='true'

# Required by the do283 shlib
this='secure-jwt'
title='GE: Authenticating and Authorizing Requests'

declare -a valid_commands=(start finish)

function lab_start {

  ocp4_print_setup_header
  ocp4_grab_lab_files
  ocp4_print_setup_footer

}

function lab_finish {

  ocp4_print_cleanup_header

  ocp4_cleanup_lab_files

  ocp4_print_cleanup_footer

}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
