#!/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-test - lab script to demo and test new platform shlib functions
#
# SYNOPSIS
#     lab-test {pad2|cnfh}
#
#        pad2 - test the pad2 function
#        cnfh - test the command not found handler
#
# DESCRIPTION
#     This script, based on singular argument, tests a function
#
# CHANGELOG
#   * Mon Sep 21 2020 FJordi Sola <jordisola@redhat.com>
#   - original code
#
# REFERENCES
#     Applications
#         This lab does not use any applications


PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

# Initialize and set some variables
run_as_root='true'
this='apps-connect'
title='Guided Exercise: Implementing Service Discovery with OpenShift'
target='workstation'
RHT_OCP4_CONFIG=/usr/local/etc/ocp4.config

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish grade)

function lab_start {

  ocp4_print_prereq_header

  ocp4_login_as_developer

  ocp4_print_setup_header

  ocp4_grab_lab_files

  ocp4_new_project ${RHT_OCP4_DEV_USER}-${this}

  ocp4_print_setup_footer
}

#Grade is ONLY for end of chapter labs!
function lab_grade {

  ocp4_print_grade_header


  pad2 "${this} is present"
  if ${this}; then
    print_PASS
  else
    print_FAIL
  fi


  ocp4_print_grade_footer
}


function lab_finish {

  ocp4_print_cleanup_header

  ocp4_delete_project ${RHT_OCP4_DEV_USER}-${this}

  ocp4_cleanup_lab_files

  ocp4_print_cleanup_footer
}



############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
